blueprint:
  name: AL - Ambiance Lighting (Brightness & Color Temperature)
  description: |
    Uses the 'Automatic Lighting' integration to create a profile that will turn on lighting when no trigger is triggered.
  domain: automation
  input:
    al_entity:
      name: Automatic Lighting Entity
      description: The 'Automatic Lighting' entity used to track the lighting.
      selector:
        entity:
          integration: automatic_lighting
    lights:
      name: Lights
      description: The lights that should be turned on.
      selector:
        target:
          entity:
            domain: light
    time_after:
      name: After
      description: The time after which the lights can be turned on.
      default: "00:00:00"
      selector:
        time:
    time_before:
      name: Before
      description: The time before which the lights can be turned on.
      default: "23:59:59"
      selector:
        time:
    illuminance_entity:
      name: Daylight Sensor
      description: The entity that measures the amount of daylight.
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: illuminance
    illuminance_max:
      name: Max Daylight Value
      description: The maximum amount of daylight allowed.
      default: 100
      selector:
        number:
          mode: box
          min: 1
          max: 100000
          unit_of_measurement: lx
    brightness:
      name: Brightness
      description: The brightness (in %) that the lights should be set to when turned on.
      default: 100
      selector:
        number:
          mode: slider
          min: 1
          max: 100
          step: 1
          unit_of_measurement: "%"
    color_temp:
      name: Color Temperature
      description: The color temperature (in kelvin) that the lights should be set to when turned on.
      default: 3000
      selector:
        number:
          mode: slider
          min: 2200
          max: 6500
          step: 25
          unit_of_measurement: K

max_exceeded: silent
mode: restart

variables:
  illuminance_entity: !input illuminance_entity
  illuminance_max: !input illuminance_max

trigger:
  - platform: event
    event_type: automation_reloaded
  - platform: event
    event_type: automatic_lighting_event
    event_data:
      entity_id: !input al_entity
      type: refresh
  - platform: time
    at: !input time_after
  - platform: state
    entity_id: !input illuminance_entity
condition:
  - condition: time
    after: !input time_after
    before: !input time_before
  - condition: numeric_state
    entity_id: !input illuminance_entity
    below: !input illuminance_max
action:
  - variables:
      id: >-
        {% set ns = namespace(unique_id=[]) %}
        {% for i in range(0, 10) %}
          {% set ns.unique_id = ns.unique_id + [[0,1,2,3,4,5,6,7,8,9]|random] %}
        {% endfor %}
        {{ ns.unique_id|join("") }}
  - service: automatic_lighting.turn_on
    data:
      entity_id: !input al_entity
      id: "{{ id }}"
      type: ambiance
      lights: !input lights
      brightness: !input brightness
      kelvin: !input color_temp
  - wait_for_trigger:
      - platform: time
        at: !input time_before
      - platform: numeric_state
        entity_id: !input illuminance_entity
        above: !input illuminance_max
  - service: automatic_lighting.turn_off
    data:
      entity_id: !input al_entity
      id: "{{ id }}"
