blueprint:
  name: Test
  description: |
    Test
  domain: automation
  input:
    lights:
      name: Lights
      description: The lights that should be turned on.
      selector:
        target:
          entity:
            domain: light

max_exceeded: silent
mode: restart

trigger: []
condition: []
action:
  - service: light.turn_on
    target: !input lights
    data:
      brightness: 50